services:
  - type: web
    name: gcc2050
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app -w 2 -b :10000
    repo: https://github.com/alpha-1-design/Gracemanager-
    branch: main