services:
  - type: web
    name: gcc2050
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app --workers 2 --bind 0.0.0.0:$PORT
    repo: https://github.com/alpha-1-design/Gracemanager-
    branch: main